<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
	<RazorLangVersion>9.0</RazorLangVersion>
	<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
	<Version>1.0.61</Version>
	<Authors>Artem</Authors>
	<Company>AshberryTogether</Company>
	<Description>Ryabina Blazor Components</Description>
	<PackageTags>blazor;ryacomponents;ui</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Components\Common\DateBox\RyaDateBox.razor.js" />
    <Content Include="Components\Common\Dialogs\DropDown\RyaDropDown.razor.js" />
    <Content Include="Components\Common\Dialogs\PopupBase.razor.js" />
    <Content Include="Components\Common\Dialogs\Popup\RyaPopup.razor.js" />
    <Content Include="Components\Common\FloatingButton\RyaFloatingButton.razor.js" />
    <Content Include="Components\Common\Menu\RyaMenu.razor.js" />
    <Content Include="Components\Common\UploadBox\RyaUploadBox.razor.js" />
  </ItemGroup>

  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="9.0.5" />
  </ItemGroup>

</Project>
